"""Tests for core.ingestion.normalizer.

Two parametrized layers:
  1. Hard-coded ANCHOR_CASES (the 9 cases the brief mandates).
  2. Every fixture in qb_entities.json + ruddr_entities.json compared against
     tests/fixtures/normalizer_expected.json (golden file).

The golden file is regenerated by tests/regenerate_normalizer_expected.py.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from core.ingestion.normalizer import (  # noqa: E402
    NormalizationError,
    NormalizedEntity,
    normalize_entity,
)


FIXTURE_DIR = REPO / "tests" / "fixtures"


# ---------------------------------------------------------------------------
# Anchor cases
# ---------------------------------------------------------------------------

ANCHOR_CASES = [
    ("Cenlar, LLC.", "organization", "quickbooks", "cenlar"),
    ("Chen, Michael", "person", "quickbooks", "michael chen"),
    ("André Dubois", "person", "quickbooks", "andre dubois"),
    ("The Briarwood Group, LLC", "organization", "quickbooks",
     "briarwood group"),
    ("Pinnacle Engineering (Northeast)", "organization", "quickbooks",
     "pinnacle engineering"),
    ("Beck & Howell Consulting Group", "organization", "quickbooks",
     "beck and howell consulting group"),
    ("Marcus Williams Jr.", "person", "quickbooks", "marcus williams"),
    ("Sarah J. Martinez", "person", "quickbooks", "sarah martinez"),
    ("GreenField Analytics, LLC", "organization", "quickbooks",
     "greenfield analytics"),
]


@pytest.mark.parametrize(
    "raw_name,entity_category,source,expected",
    ANCHOR_CASES,
    ids=[c[0] for c in ANCHOR_CASES],
)
def test_anchor_case(raw_name, entity_category, source, expected):
    result = normalize_entity({
        "id": "ANCHOR",
        "source": source,
        "entity_category": entity_category,
        "display_name": raw_name,
    })
    assert isinstance(result, NormalizedEntity)
    assert result.normalized_name == expected, (
        f"raw={raw_name!r} expected={expected!r} got={result.normalized_name!r}"
    )


# ---------------------------------------------------------------------------
# Fixture parametrization (all 91 entities vs. golden file)
# ---------------------------------------------------------------------------


def _load_fixtures():
    qb = json.loads((FIXTURE_DIR / "qb_entities.json").read_text())
    rd = json.loads((FIXTURE_DIR / "ruddr_entities.json").read_text())
    return qb + rd


def _load_expected():
    return json.loads((FIXTURE_DIR / "normalizer_expected.json").read_text())


_FIXTURES = _load_fixtures()
_EXPECTED = _load_expected()


@pytest.mark.parametrize(
    "entity",
    _FIXTURES,
    ids=[e["id"] for e in _FIXTURES],
)
def test_fixture_matches_expected(entity):
    expected = _EXPECTED.get(entity["id"])
    assert expected is not None, f"no expected entry for {entity['id']}"
    result = normalize_entity(entity)
    assert result.normalized_name == expected, (
        f"id={entity['id']} raw={entity.get('display_name')!r} "
        f"expected={expected!r} got={result.normalized_name!r}"
    )


# ---------------------------------------------------------------------------
# Output-shape sanity checks
# ---------------------------------------------------------------------------


def test_source_to_category_quickbooks():
    e = {"id": "QB-X", "source": "quickbooks",
         "entity_category": "organization", "display_name": "Acme"}
    out = normalize_entity(e)
    assert out.category == "accounting"


def test_source_to_category_ruddr():
    e = {"id": "RD-X", "source": "ruddr",
         "entity_category": "organization", "display_name": "Acme"}
    out = normalize_entity(e)
    assert out.category == "psa"


def test_email_extracted_for_person():
    e = {"id": "QB-Z", "source": "quickbooks",
         "entity_category": "person", "display_name": "Jane Doe",
         "email": "jane@example.com"}
    out = normalize_entity(e)
    assert out.email == "jane@example.com"
    assert out.email_is_person is True


def test_email_extracted_for_org_but_flagged_non_person():
    e = {"id": "QB-Y", "source": "quickbooks",
         "entity_category": "organization", "display_name": "Acme Inc",
         "email": "billing@acme.com"}
    out = normalize_entity(e)
    assert out.email == "billing@acme.com"
    assert out.email_is_person is False


def test_raw_record_preserved_opaquely():
    e = {"id": "QB-W", "source": "quickbooks",
         "entity_category": "organization", "display_name": "Acme",
         "balance": 123.45, "address": {"city": "NYC"}}
    out = normalize_entity(e)
    assert out.raw_record is e
    assert out.raw_record["balance"] == 123.45
    assert out.raw_record["address"] == {"city": "NYC"}


def test_empty_name_raises():
    with pytest.raises(NormalizationError):
        normalize_entity({
            "id": "QB-E", "source": "quickbooks",
            "entity_category": "organization", "display_name": "",
        })


def test_missing_name_raises():
    with pytest.raises(NormalizationError):
        normalize_entity({
            "id": "QB-E2", "source": "quickbooks",
            "entity_category": "organization",
        })


def test_whitespace_only_name_raises():
    with pytest.raises(NormalizationError):
        normalize_entity({
            "id": "QB-E3", "source": "quickbooks",
            "entity_category": "organization", "display_name": "    ",
        })


def test_rules_applied_includes_lowercase_always():
    out = normalize_entity({
        "id": "X", "source": "quickbooks",
        "entity_category": "organization", "display_name": "Foo",
    })
    assert "lowercase" in out.rules_applied


def test_rules_applied_records_legal_suffix_strip():
    out = normalize_entity({
        "id": "X", "source": "quickbooks",
        "entity_category": "organization", "display_name": "Foo, LLC",
    })
    assert "strip_legal_suffix" in out.rules_applied
